name: MNN Windows

on: [ workflow_dispatch ]

jobs:
  build:
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2

    - name: Download MNN code
      run: |
        mkdir work
        cd work
        git clone https://github.com/alibaba/MNN.git
        cd MNN
        git checkout 1.2.6

    - name: Build
      run: |
        cd ~/work/MNN
        ~/mnn/build_mnn_windows.ps1

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: mnn_prebuilt_windows.zip
        path: ~/work/MNN/mnn_prebuilt_windows.zip
