name: MNN Linux

on:
  push:
    tags: '*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: bash ./mnn/build_mnn_linux.sh

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: mnn_prebuilt_linux.tgz
        path: mnn_prebuilt_linux.tgz

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          mnn_prebuilt_linux.tgz
          NOTICE.md
