name: TfLite Windows

on:
  push:
    tags: '*'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2

    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v1.1

    - name: Install ninja-build tool
      uses: seanmiddleditch/gha-setup-ninja@v3

    - name: Install Bazel
      run: |
        mkdir bin
        curl -L https://github.com/bazelbuild/bazel/releases/download/4.2.2/bazel-4.2.2-windows-x86_64.zip -o temp.zip
        powershell Expand-Archive -Path temp.zip -DestinationPath ./bin
        $env:path = "$(pwd)/bin;" + $env:path

    - uses: actions/setup-python@v2
      with:
        python-version: '3.8'
        architecture: 'x64'

    - name: Check Environment
      run: |
        ./bin/bazel version
        python -V
        python3 -V
        which python
        # which bazel

    - name: Build
      run: |
        ./tflite/build_tflite_windows.ps1

    # - name: Build
    #   run: |
    #     mkdir temp
    #     cd temp
    #     ../mnn/build_mnn_windows.ps1

    # - name: Upload Artifacts
    #   uses: actions/upload-artifact@v2
    #   with:
    #     name: mnn_prebuilt_windows.zip
    #     path: ./temp/mnn_prebuilt_windows.zip

    # - name: Release
    #   uses: softprops/action-gh-release@v1
    #   if: startsWith(github.ref, 'refs/tags/')
    #   with:
    #     draft: true
    #     files: |
    #       ./temp/mnn_prebuilt_windows.zip
    #       ACKNOWLEDGEMENTS.md
