name: TfLite Windows

on:
  push:
    tags: '*'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2

    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v1.1
      with:
        vs-version: '[16.0,16.20)'  # Make sure to use Visual Studio 2019

    - name: Check Environment
      run: |
        # ./bin/bazel version
        python -V
        python3 -V
        which python
        # which bazel

    - name: Build
      run: |
        ./tflite/build_tflite_windows.ps1

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: tflite_prebuilt_windows.zip
        path: ./tflite_prebuilt_windows.zip

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        draft: true
        files: |
          ./tflite_prebuilt_windows.zip
          ACKNOWLEDGEMENTS.md
