name: EdgeTPU Windows

on:
  push:
    tags: '*'
  workflow_dispatch:

env:
  USE_BAZEL_VERSION: 4.2.1

jobs:
  build:
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2

    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v1.1
      with:
        vs-version: '[16.0,16.20)'  # Make sure to use Visual Studio 2019

    - name: Build
      run: |
        # By default, I can't use rc.exe (reference: https://github.com/actions/virtual-environments/issues/294)
        function Invoke-VSDevEnvironment {
            $vswhere = "${env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vswhere.exe"
            $installationPath = & $vswhere -prerelease -legacy -latest -property installationPath
            $Command = Join-Path $installationPath "Common7\Tools\vsdevcmd.bat"
             & "${env:COMSPEC}" /s /c "`"$Command`" -no_logo && set" | Foreach-Object {
                if ($_ -match '^([^=]+)=(.*)') {
                    [System.Environment]::SetEnvironmentVariable($matches[1], $matches[2])
                }
            }
        }
        Invoke-VSDevEnvironment
        Get-Command rc.exe | Format-Table -AutoSize
        rc.exe 
        
        ./edgetpu/build_edgetpu_windows.ps1

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: edgetpu_prebuilt_windows.zip
        path: ./edgetpu_prebuilt_windows.zip

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        draft: true
        files: |
          ./edgetpu_prebuilt_windows.zip
          ACKNOWLEDGEMENTS.md

